export const EMAILS_MEDICAL_SPAM = [
  { subject: 'Confirmación de turno - Dr. Gómez', fromName: 'Clínica SaluVida', fromEmail: 'notices@saludvida-care.net', body: 'Confirmá tu turno con Dr. Gómez. Confirmá aquí: https://calenda.com/confirm?day=1&time=09:00&title=Dr.%20Gómez', isSpam: true, type: 'medical' },
  { subject: 'Turno odontológico - Dra. Pérez', fromName: 'Centro Dental Sonrisas', fromEmail: 'avisos@dentalsonrisas-info.org', body: 'Confirmá tu turno con Dra. Pérez. Confirmá aquí: https://calenda.com/confirm?day=2&time=11:30&title=Dra.%20Pérez', isSpam: true, type: 'medical' },
  { subject: 'Ecografía - Dra. Morales', fromName: 'Diagnóstico Integral', fromEmail: 'updates@diag-integral.app', body: 'Confirmá tu turno de ecografía con Dra. Morales. Confirmá aquí: https://calenda.com/confirm?day=3&time=08:30&service=Ecografía&title=Dra.%20Morales', isSpam: true, type: 'medical' },
  { subject: 'Vacunación - Centro Municipal', fromName: 'Vacunatorio Municipal', fromEmail: 'recordatorios@vacunas-gob-ar.co', body: 'Confirmá tu turno de vacunación. Confirmá aquí: https://calenda.com/confirm?day=4&time=10:00&service=Vacunación', isSpam: true, type: 'medical' },
  { subject: 'Consulta cardiología - Dr. Silva', fromName: 'Clínica CardioPlus', fromEmail: 'citas@cardioplus-services.pro', body: 'Confirmá tu turno con Dr. Silva. Confirmá aquí: https://calenda.com/confirm?day=5&time=14:00&title=Dr.%20Silva', isSpam: true, type: 'medical' },
  { subject: 'Análisis de laboratorio', fromName: 'Laboratorio Central', fromEmail: 'lab@central-labs.online', body: 'Confirmá tu turno de análisis. Confirmá aquí: https://calenda.com/confirm?day=6&time=08:15&service=Laboratorio', isSpam: true, type: 'medical' },
  { subject: 'Resonancia - Dr. Navarro', fromName: 'Centro Diagnóstico Norte', fromEmail: 'citas@cdnorte-check.net', body: 'Confirmá tu resonancia con Dr. Navarro. Confirmá aquí: https://calenda.com/confirm?day=7&time=13:00&service=Resonancia&title=Dr.%20Navarro', isSpam: true, type: 'medical' },
  { subject: 'Consulta ginecológica - Dra. López', fromName: 'Centro Médico del Sur', fromEmail: 'agenda@cmsur-health.biz', body: 'Confirmá tu turno con Dra. López. Confirmá aquí: https://calenda.com/confirm?day=8&time=09:45&title=Dra.%20López', isSpam: true, type: 'medical' },
  { subject: 'Consulta dermatológica - Dr. Vega', fromName: 'Clínica DermaCare', fromEmail: 'alerts@dermacare-support.me', body: 'Confirmá tu turno con Dr. Vega. Confirmá aquí: https://calenda.com/confirm?day=9&time=15:15&title=Dr.%20Vega', isSpam: true, type: 'medical' },
  { subject: 'Chequeo general - Dra. Ruiz', fromName: 'Instituto Médico Horizonte', fromEmail: 'notices@imhorizonte-service.io', body: 'Confirmá tu chequeo con Dra. Ruiz. Confirmá aquí: https://calenda.com/confirm?day=10&time=11:00&title=Dra.%20Ruiz', isSpam: true, type: 'medical' },
];