const BANK_NAME = 'Banco Nación';
const BANK_EMAIL = 'notificaciones@bna.com.ar';
const BANK_URL = 'https://bna.com.ar/';

export const EMAILS_BANK_LEGIT = [
    { subject: 'Resumen mensual disponible', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Ya podés descargar el resumen de tu cuenta corriente del mes de septiembre. https://bna.com.ar/resumen', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Resteo de contraseña', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Ya podés descargar el resumen de tu cuenta corriente del mes de septiembre. https://bna.com.ar/resumen', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Nueva actividad en tu cuenta', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Se ha detectado una nueva actividad en tu cuenta. Ingresá para más detalles. https://bna.com.ar/actividad', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Actualización de datos personales', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Recordá mantener tus datos personales actualizados para una mejor atención. https://bna.com.ar/actualizacion', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Promoción exclusiva para clientes', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Aprovechá nuestra promoción exclusiva para clientes del Banco Nación. Más info en https://bna.com.ar/promociones', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Invitación a webinar financiero', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Te invitamos a nuestro próximo webinar sobre finanzas personales. Inscribite aquí: https://bna.com.ar/webinar', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Aviso de mantenimiento programado', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'El sistema estará en mantenimiento el domingo de 1 a 5 AM. Algunos servicios pueden verse afectados.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Comprobante de transferencia disponible', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Tu comprobante de transferencia ya está disponible para descargar desde el homebanking.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Nuevo mensaje en tu buzón electrónico', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Ingresá a tu banca online para leer un nuevo mensaje importante.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Límite de tarjeta actualizado', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Tu límite de tarjeta ha sido actualizado. Podés consultarlo en tu panel.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Aviso de débito automático', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Se registró un débito automático en tu cuenta. Revisá los detalles ingresando al homebanking.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Nuevo documento disponible', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Hay un nuevo documento disponible en tu bandeja de notificaciones. Consultalo cuando quieras.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Recordatorio de vencimiento de tarjeta', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Tu tarjeta está próxima a vencer. Te enviaremos una nueva de manera automática.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Confirmación de cambio de alias', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Tu alias bancario fue actualizado exitosamente. Si no fuiste vos, comunicate con soporte.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Actualización de términos y condiciones', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Se actualizaron nuestros términos y condiciones. Podés revisarlos en nuestro sitio.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Registro de inicio de sesión', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Detectamos un nuevo inicio de sesión en tu cuenta. Revisá la actividad si no fuiste vos.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Estado de solicitud actualizado', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'El estado de tu solicitud fue actualizado. Consultalo desde tu homebanking.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Aviso de crédito acreditado', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Tu crédito fue acreditado exitosamente en tu cuenta.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Info importante sobre tu tarjeta de débito', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Te recordamos activar tu tarjeta de débito antes de usarla en cajeros o comercios.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Tu resumen de tarjeta ya está disponible', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Ya podés consultar el resumen actualizado de tu tarjeta desde tu cuenta online.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },
    { subject: 'Verificación de identidad pendiente', fromName: BANK_NAME, fromEmail: BANK_EMAIL, body: 'Para continuar operando con normalidad, recordá completar la verificación de identidad.', isSpam: false, type: 'finance', content: 'captcha', url: BANK_URL },

]