export const EMAILS_WORK_SPAM = [
  { subject: 'Confirmación de reunión', fromName: 'Acme Corp', fromEmail: 'notify@calendar-secure.net', body: 'Confirmá tu asistencia para "Sprint Planning". Confirmá aquí: https://calendr.com/confirm?day=1&time=10:00&meeting=Sprint%20Planning', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Reunión de equipo semanal', fromName: 'Acme Corp', fromEmail: 'updates@workmeetings.pro', body: 'Confirmá tu asistencia para "Team Sync". Confirmá aquí: https://calendr.com/confirm?day=2&time=11:30&meeting=Team%20Sync', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Agendado: Revisión de diseño', fromName: 'Acme Corp', fromEmail: 'design@corporate-tools.io', body: 'Confirmá tu asistencia para "UI Review". Confirmá aquí: https://calendr.com/confirm?day=3&time=15:00&meeting=UI%20Review', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Actualización de proyecto', fromName: 'Acme Corp', fromEmail: 'status@corp-dashboard.app', body: 'Confirmá tu asistencia para "Status Update". Confirmá aquí: https://calendr.com/confirm?day=4&time=09:00&meeting=Status%20Update', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Reunión con dirección', fromName: 'Acme Corp', fromEmail: 'admin@mgmt-brief.net', body: 'Confirmá tu asistencia para "Management Briefing". Confirmá aquí: https://calendr.com/confirm?day=5&time=16:00&meeting=Management%20Briefing', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Feedback de sprint anterior', fromName: 'Acme Corp', fromEmail: 'sprints@feedback-tools.co', body: 'Confirmá tu asistencia para "Retrospectiva". Confirmá aquí: https://calendr.com/confirm?day=6&time=14:00&meeting=Retrospectiva', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Presentación interna', fromName: 'Acme Corp', fromEmail: 'demo@weekly-insight.biz', body: 'Confirmá tu asistencia para "Demo Semanal". Confirmá aquí: https://calendr.com/confirm?day=7&time=13:00&meeting=Demo%20Semanal', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Planificación mensual', fromName: 'Acme Corp', fromEmail: 'plan@month-schedule.org', body: 'Confirmá tu asistencia para "Monthly Planning". Confirmá aquí: https://calendr.com/confirm?day=8&time=11:00&meeting=Monthly%20Planning', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Evaluación de desempeño', fromName: 'Acme Corp', fromEmail: 'review@hr-eval.online', body: 'Confirmá tu asistencia para "Performance Review". Confirmá aquí: https://calendr.com/confirm?day=9&time=10:30&meeting=Performance%20Review', isSpam: true, type: 'work', content: 'apointment' },
  { subject: 'Reunión de coordinación', fromName: 'Acme Corp', fromEmail: 'ops@weekly-ops.me', body: 'Confirmá tu asistencia para "Operaciones Semanales". Confirmá aquí: https://calendr.com/confirm?day=10&time=09:30&meeting=Operaciones%20Semanales', isSpam: true, type: 'work', content: 'apointment' },
];