export const EMAILS_MEDICAL_LEGIT = [
  { subject: 'Confirmación de turno - Dr. Gómez', fromName: 'Clínica SaluVida', fromEmail: 'turnos@saludvida.com', body: 'Confirmá tu turno con Dr. Gómez. Confirmá aquí: https://calendar.com/confirm?day=2&time=09:00&title=Dr.%20Gómez', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=2&time=09:00&title=Dr.%20Gómez' },
  { subject: 'Turno odontológico - Dra. Pérez', fromName: 'Centro Dental Sonrisas', fromEmail: 'turnos@dentalsonrisas.com', body: 'Confirmá tu turno con Dra. Pérez. Confirmá aquí: https://calendar.com/confirm?day=3&time=11:30&title=Dra.%20Pérez', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=3&time=11:30&title=Dra.%20Pérez' },
  { subject: 'Ecografía - Dra. Morales', fromName: 'Diagnóstico Integral', fromEmail: 'turnos@diag-integral.com', body: 'Confirmá tu turno de ecografía con Dra. Morales. Confirmá aquí: https://calendar.com/confirm?day=5&time=08:30&service=Ecografía&title=Dra.%20Morales', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=5&time=08:30&service=Ecografía&title=Dra.%20Morales' },
  { subject: 'Vacunación - Centro Municipal', fromName: 'Vacunatorio Municipal', fromEmail: 'turnos@vacunatorio.gob.ar', body: 'Confirmá tu turno de vacunación. Confirmá aquí: https://calendar.com/confirm?day=4&time=10:00&service=Vacunación', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=4&time=10:00&service=Vacunación' },
  { subject: 'Consulta cardiología - Dr. Silva', fromName: 'Clínica CardioPlus', fromEmail: 'turnos@cardioplus.com', body: 'Confirmá tu turno con Dr. Silva. Confirmá aquí: https://calendar.com/confirm?day=7&time=14:00&title=Dr.%20Silva', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=7&time=14:00&title=Dr.%20Silva' },
  { subject: 'Análisis de laboratorio', fromName: 'Laboratorio Central', fromEmail: 'turnos@labcentral.com', body: 'Confirmá tu turno de análisis. Confirmá aquí: https://calendar.com/confirm?day=2&time=08:15&service=Laboratorio', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=2&time=08:15&service=Laboratorio' },
  { subject: 'Resonancia - Dr. Navarro', fromName: 'Centro Diagnóstico Norte', fromEmail: 'turnos@cdnorte.com', body: 'Confirmá tu turno de resonancia. Confirmá aquí: https://calendar.com/confirm?day=3&time=13:00&service=Resonancia&title=Dr.%20Navarro', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=3&time=13:00&service=Resonancia&title=Dr.%20Navarro' },
  { subject: 'Turno ginecológico - Dra. López', fromName: 'Centro Médico del Sur', fromEmail: 'turnos@cmsur.com', body: 'Confirmá tu turno con Dra. López. Confirmá aquí: https://calendar.com/confirm?day=6&time=09:45&title=Dra.%20López', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=6&time=09:45&title=Dra.%20López' },
  { subject: 'Consulta dermatológica - Dr. Vega', fromName: 'Clínica DermaCare', fromEmail: 'turnos@dermacare.com', body: 'Confirmá tu turno con Dr. Vega. Confirmá aquí: https://calendar.com/confirm?day=5&time=15:15&title=Dr.%20Vega', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=5&time=15:15&title=Dr.%20Vega' },
  { subject: 'Chequeo general - Dra. Ruiz', fromName: 'Instituto Médico Horizonte', fromEmail: 'turnos@imhorizonte.com', body: 'Confirmá tu chequeo con Dra. Ruiz. Confirmá aquí: https://calendar.com/confirm?day=8&time=11:00&title=Dra.%20Ruiz', isSpam: false, type: 'medical', content: 'apointment', url: 'https://calendar.com/confirm?day=8&time=11:00&title=Dra.%20Ruiz' },
];