export const EMAILS = [
  { id: 1, subject: 'Bienvenido a tu correo y novedades.', from: 'Soporte Técnico', date: '24/09/2025', body: 'Te damos la bienvenida a tu nuevo correo. Aquí recibirás novedades y soporte.', isSpam: false },
  { id: 2, subject: 'Oferta especial: descuentos exclusivos.', from: 'María López', date: '23/09/2025', body: 'Aprovecha descuentos exclusivos en nuestra tienda online. Oferta limitada.', isSpam: true },
  { id: 3, subject: 'Recordatorio de reunión mañana 10:00.', from: 'Recursos Humanos', date: '22/09/2025', body: 'No olvides la reunión programada para mañana a las 10:00 en la sala principal.', isSpam: false },
  { id: 4, subject: 'Factura de septiembre lista para descargar.', from: 'Contabilidad', date: '21/09/2025', body: 'Tu factura de septiembre ya está disponible para descargar en el portal.', isSpam: true },
  { id: 5, subject: 'Actualización de políticas de uso.', from: 'Legal', date: '20/09/2025', body: 'Consulta las nuevas políticas de uso que entrarán en vigor este mes.', isSpam: true },
  { id: 6, subject: 'Invitación: webinar productividad digital.', from: 'Ana Torres', date: '19/09/2025', body: 'Participa en nuestro webinar sobre productividad digital. Regístrate aquí.', isSpam: true },
  { id: 7, subject: 'Confirmación de registro al curso.', from: 'Academia Online', date: '18/09/2025', body: 'Tu registro al curso ha sido confirmado. Próximamente recibirás más información.', isSpam: false },
  { id: 8, subject: '¡Feliz cumpleaños! Que tengas un gran día.', from: 'Juan Pérez', date: '17/09/2025', body: '¡Feliz cumpleaños! Esperamos que tengas un día increíble junto a tus seres queridos.', isSpam: true },
  { id: 9, subject: 'Alerta: inicio de sesión nuevo dispositivo.', from: 'Seguridad', date: '16/09/2025', body: 'Detectamos un inicio de sesión desde un nuevo dispositivo. Si no fuiste tú, cambia tu contraseña.', isSpam: true },
  { id: 10, subject: 'Boletín mensual: noticias y logros.', from: 'Comunicaciones', date: '15/09/2025', body: 'Descubre las últimas noticias y logros de nuestra organización en el boletín mensual.', isSpam: true },
  { id: 11, subject: 'Solicitud de soporte recibida.', from: 'Atención al Cliente', date: '14/09/2025', body: 'Hemos recibido tu solicitud de soporte. Pronto nos pondremos en contacto contigo.', isSpam: false },
  { id: 12, subject: 'Encuesta de satisfacción de servicios.', from: 'Equipo de Calidad', date: '13/09/2025', body: 'Ayúdanos a mejorar completando la encuesta de satisfacción de nuestros servicios.', isSpam: false },
  { id: 13, subject: 'Notificación: tu pedido está en camino.', from: 'Logística', date: '12/09/2025', body: 'Tu pedido ha sido enviado y está en camino. Puedes rastrearlo en el portal.', isSpam: false },
  { id: 14, subject: 'Actualización de software disponible.', from: 'Desarrollo', date: '11/09/2025', body: 'Hay una nueva actualización de software disponible. Descárgala para mejorar tu experiencia.', isSpam: false },
  { id: 15, subject: 'Invitación a evento de networking.', from: 'Organización', date: '10/09/2025', body: 'Te invitamos a nuestro evento de networking para ampliar tu red profesional.', isSpam: false },
  { id: 16, subject: 'Recordatorio: saldo pendiente de pago.', from: 'Cobranzas', date: '09/09/2025', body: 'Tienes un saldo pendiente de pago. Por favor, regulariza tu situación lo antes posible.', isSpam: false },
  { id: 17, subject: 'Bienvenido a la comunidad.', from: 'Equipo de Comunidad', date: '08/09/2025', body: '¡Bienvenido! Ahora eres parte de nuestra comunidad. Explora y participa.', isSpam: false },
  { id: 18, subject: 'Completa tu perfil para más funciones.', from: 'Administración', date: '07/09/2025', body: 'Completa tu perfil para acceder a más funciones y beneficios en la plataforma.', isSpam: false },
  { id: 19, subject: 'Participa en nuestra encuesta anual.', from: 'Investigación', date: '06/09/2025', body: 'Tu opinión es importante. Participa en nuestra encuesta anual y ayúdanos a mejorar.', isSpam: false },
  { id: 20, subject: 'Aviso: mantenimiento el sábado 2-6 AM.', from: 'Infraestructura', date: '05/09/2025', body: 'Habrá mantenimiento programado el sábado de 2 a 6 AM. El servicio podría verse afectado.', isSpam: false },
  { id: 21, subject: 'Nuevo mensaje en tu buzón.', from: 'Sergio Gómez', date: '04/09/2025', body: 'Has recibido un nuevo mensaje en tu buzón. Revisa tu correo para más detalles.', isSpam: false },
  { id: 22, subject: 'Actualización de tu pedido.', from: 'Tienda Online', date: '03/09/2025', body: 'Tu pedido ha sido actualizado. Consulta el estado en tu cuenta.', isSpam: false },
  { id: 23, subject: 'Reunión de seguimiento semanal.', from: 'Coordinación', date: '02/09/2025', body: 'Recuerda la reunión de seguimiento semanal. Agenda y participa.', isSpam: true },
  { id: 24, subject: 'Invitación a grupo de trabajo.', from: 'Marta Ruiz', date: '01/09/2025', body: 'Te invitamos a formar parte de un nuevo grupo de trabajo. Confirma tu asistencia.', isSpam: false },
  { id: 25, subject: 'Confirmación de asistencia evento.', from: 'Eventos', date: '31/08/2025', body: 'Gracias por confirmar tu asistencia al evento. Te esperamos.', isSpam: false },
  { id: 26, subject: 'Actualización de contraseña exitosa.', from: 'Seguridad', date: '30/08/2025', body: 'Tu contraseña ha sido actualizada exitosamente. Mantén tu cuenta segura.', isSpam: true },
  { id: 27, subject: 'Nuevo comentario en tu publicación.', from: 'Red Social', date: '29/08/2025', body: 'Alguien ha comentado en tu publicación. Ingresa para responder o ver el comentario.', isSpam: true },
  { id: 28, subject: 'Recordatorio: cita médica mañana.', from: 'Clínica Salud', date: '28/08/2025', body: 'Recuerda tu cita médica programada para mañana. No olvides llevar tu documentación.', isSpam: true },
  { id: 29, subject: 'Tu suscripción ha sido renovada.', from: 'Suscripciones', date: '27/08/2025', body: 'Tu suscripción se ha renovado correctamente. Disfruta de los beneficios.', isSpam: false },
  { id: 30, subject: 'Mensaje de bienvenida al foro.', from: 'Foro Comunidad', date: '26/08/2025', body: 'Bienvenido al foro de la comunidad. Comparte y aprende con otros miembros.', isSpam: false },
  { id: 31, subject: 'Actualización de horarios de atención.', from: 'Atención al Cliente', date: '25/08/2025', body: 'Los horarios de atención han sido actualizados. Consulta los nuevos horarios.', isSpam: false },
  { id: 32, subject: 'Nuevo archivo compartido contigo.', from: 'Carlos Méndez', date: '24/08/2025', body: 'Carlos Méndez ha compartido un archivo contigo. Descárgalo desde tu cuenta.', isSpam: true },
  { id: 33, subject: 'Invitación a encuesta de calidad.', from: 'Calidad', date: '23/08/2025', body: 'Participa en nuestra encuesta de calidad y ayúdanos a mejorar nuestros servicios.', isSpam: false },
  { id: 34, subject: 'Notificación de pago recibido.', from: 'Finanzas', date: '22/08/2025', body: 'Tu pago ha sido recibido correctamente. Gracias por tu confianza.', isSpam: false },
  { id: 35, subject: 'Actualización de perfil realizada.', from: 'Administración', date: '21/08/2025', body: 'Tu perfil ha sido actualizado. Revisa los cambios en tu cuenta.', isSpam: true },
  { id: 36, subject: 'Nuevo acceso desde dispositivo.', from: 'Seguridad', date: '20/08/2025', body: 'Se ha detectado un nuevo acceso desde un dispositivo. Verifica tu actividad.', isSpam: true },
  { id: 37, subject: 'Recordatorio: renovar membresía.', from: 'Membresías', date: '19/08/2025', body: 'Recuerda renovar tu membresía para seguir disfrutando de nuestros servicios.', isSpam: false },
  { id: 38, subject: 'Mensaje de soporte técnico.', from: 'Soporte', date: '18/08/2025', body: 'Nuestro equipo de soporte técnico está disponible para ayudarte en lo que necesites.', isSpam: false },
  { id: 39, subject: 'Actualización de términos de uso.', from: 'Legal', date: '17/08/2025', body: 'Consulta los nuevos términos de uso que aplican a partir de este mes.', isSpam: false },
  { id: 40, subject: 'Invitación a taller online.', from: 'Talleres', date: '16/08/2025', body: 'Participa en nuestro taller online y mejora tus habilidades profesionales.', isSpam: false },
];
