const GIRLFRIEND_NAME = "💚 Cari";
const GIRLFRIEND_EMAIL = "carinacariño@gmail.com";

export const EMAILS_GIRLFRIEND_LEGIT = [
  { subject: 'Película esta noche?', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Propongo ver esa comedia que te gusta. Palomitas y manta?', isSpam: false, type: 'girlfriend' },
  { subject: 'Recordatorio médico', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'No te olvides del turno del jueves a las 9:30. Te acompaño si querés.', isSpam: false, type: 'girlfriend' },
  { subject: 'Gracias por hoy 💛', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'La cena quedó genial. Me encantó cómo cerraste el tema en la reunión.', isSpam: false, type: 'girlfriend' },
  { subject: 'Plan para mañana', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Si te parece, vamos a caminar al parque y después café. ¿A las 10 te sirve?', isSpam: false, type: 'girlfriend' },
  { subject: 'Pequeña sorpresa 🎁', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'No te digo nada aún, solo reservá la tarde del sábado.', isSpam: false, type: 'girlfriend' },
  { subject: 'Necesito tu opinión', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: '¿Cuál te gusta más: la remera azul o la verde? Te mando fotos.', isSpam: false, type: 'girlfriend' },
  { subject: 'Buena suerte hoy 🍀', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Vas a romperla en la presentación. Estoy segura.', isSpam: false, type: 'girlfriend' },
  { subject: 'Horario del dentista', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Me cambiaron el turno al miércoles 14:00. Te aviso por si querés venir.', isSpam: false, type: 'girlfriend' },
  { subject: 'Receta fácil', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Te dejo la receta de la sopa: cebolla, zanahoria, calabaza y un toque de jengibre.', isSpam: false, type: 'girlfriend' },
  { subject: 'Mensaje rápido', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Llego tarde hoy, guardá algo de la cena porfi.', isSpam: false, type: 'girlfriend' },,
  { subject: 'Farmacia', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Pasá a buscar paracetamol y vitaminas. Gracias!', isSpam: false, type: 'girlfriend' },

  { subject: 'Decime si no es tierno', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Subí la foto acá: https://imgur.com/a/1Dfibe1X3rQ', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/01.jpg' },
  { subject: 'Mirá qué bolita dormida', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Está en la galería: https://flickr.com/photos/cari/2Hfks8Y4t', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/02.jpg' },
  { subject: 'Este te va a encantar', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Subí la foto aquí: https://drive.google.com/3Jglt9Z5uz594tSk1fEZAHXN2', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/03.jpg' },
  { subject: 'Amor de gatito', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Mirá esta belleza: https://catpicshare.net/4Khmu0A6va605uTl2gFAAIYO3', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/04.jpg' },
  { subject: 'Qué cara de inocente 😻', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Te lo mando por acá: https://postimg.cc/5Linv1B7wb7', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/05.jpg' },
  { subject: 'Desperté con esta vista', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Mirá lo que me encontré: https://ibb.co/6Mopw2C8xc8', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/06.jpg' },
  { subject: 'No podés creer esto', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Jajaja mirá: https://imgbb.com/7Npqx3D9yd9', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/07.jpg' },
  { subject: 'Foto del día ✨', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Hoy capturé esta joya: https://drive.google.com/8Oqry4E0ze0', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/08.jpg' },
  { subject: 'Posando como modelo', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Salió re bien esta: https://unsplash.com/photos/9Prsz5F1af1', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/09.jpg' },
  { subject: 'Momento de relax', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Qué paz transmite: https://pinterest.com/pin/10Qstu6G2bg', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/10.jpg' },
  { subject: 'Acá concentrado', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Modo cazador activado: https://imgur.com/a/11Rtuv7H3ch', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/11.jpg' },
  { subject: 'Siesta profunda', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Mira cómo duerme: https://flickr.com/photos/cari/12Suvw8I4di', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/12.jpg' },
  { subject: 'Travesura detectada', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Casi me hace reír en zoom: https://postimages.org/13Tvwx9J5ej', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/13.jpg' },
  { subject: 'Mirada profunda', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Esos ojitos me matan: https://imgbb.com/14Uwxy0K6fk', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/14.jpg' },
  { subject: 'Rey del sofá', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Se adueñó del sillón: https://catlover.gallery/15Vxyz1L7gl', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/15.jpg' },
  { subject: 'Jugando con luz', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Le encanta el reflejo: https://drive.google.com/16Wyza2M8hm', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/16.jpg' },
  { subject: 'Escondite fallido', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Pensó que no lo veía: https://imgur.com/a/17Xzab3N9in', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/17.jpg' },
  { subject: 'Momento zen', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Meditando felino: https://unsplash.com/photos/18Yabc4O0jo', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/18.jpg' },
  { subject: 'Explorando rincones', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Siempre curioso: https://flickr.com/photos/cari/19Zbcd5P1kp', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/19.jpg' },
  { subject: 'Belly rubs time', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Modo pancita arriba: https://postimg.cc/20Acde6Q2lq', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/20.jpg' },
  { subject: 'Recordá llamar a mamá', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Hoy es el cumple de mamá, no te olvides de saludarla.', isSpam: false, type: 'girlfriend' },
  { subject: 'Buenas noches 😘', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Que descanses y sueñes lindo.', isSpam: false, type: 'girlfriend' },
]