export const EMAILS = [
  { id: 1, subject: 'Bienvenido a tu correo y novedades.', from: 'Soporte Técnico', date: '24/09/2025', body: 'Te damos la bienvenida a tu nuevo correo. Aquí recibirás novedades y soporte.', isSpam: false },
  { id: 2, subject: 'Special offer: exclusive discounts!', from: 'Maria Lopez', date: '23/09/2025', body: 'Take advantage of exclusive discounts in our online store. Limited time offer.', isSpam: true },
  { id: 3, subject: '会议提醒：明天上午10点。', from: '人力资源部', date: '22/09/2025', body: '请不要忘记明天上午10点在主会议室的会议。', isSpam: false },
  { id: 4, subject: 'Factura de septiembre lista para descargar.', from: 'Contabilidad', date: '21/09/2025', body: 'Tu factura de septiembre ya está disponible para descargar en el portal.', isSpam: true },
  { id: 5, subject: 'Policy update: new terms.', from: 'Legal', date: '20/09/2025', body: 'Check out the new terms of use effective this month.', isSpam: true },
  { id: 6, subject: '邀请：数字生产力网络研讨会。', from: 'Ana Torres', date: '19/09/2025', body: '参加我们的数字生产力网络研讨会。立即注册。', isSpam: true },
  { id: 7, subject: 'Confirmación de registro al curso.', from: 'Academia Online', date: '18/09/2025', body: 'Tu registro al curso ha sido confirmado. Próximamente recibirás más información.', isSpam: false },
  { id: 8, subject: '¡Feliz cumpleaños! Que tengas un gran día.', from: 'Juan Pérez', date: '17/09/2025', body: '¡Feliz cumpleaños! Esperamos que tengas un día increíble junto a tus seres queridos.', isSpam: true },
  { id: 9, subject: '登录警告：新设备。', from: '安全部', date: '16/09/2025', body: '检测到新设备登录。如果不是你本人，请更改密码。', isSpam: true },
  { id: 10, subject: 'Boletín mensual: noticias y logros.', from: 'Comunicaciones', date: '15/09/2025', body: 'Descubre las últimas noticias y logros de nuestra organización en el boletín mensual.', isSpam: true },
  { id: 11, subject: 'Solicitud de soporte recibida.', from: 'Atención al Cliente', date: '14/09/2025', body: 'Hemos recibido tu solicitud de soporte. Pronto nos pondremos en contacto contigo.', isSpam: false },
  { id: 12, subject: 'Encuesta de satisfacción de servicios.', from: 'Equipo de Calidad', date: '13/09/2025', body: 'Ayúdanos a mejorar completando la encuesta de satisfacción de nuestros servicios.', isSpam: false },
  { id: 13, subject: 'Notificación: tu pedido está en camino.', from: 'Logística', date: '12/09/2025', body: 'Tu pedido ha sido enviado y está en camino. Puedes rastrearlo en el portal.', isSpam: false },
  { id: 14, subject: 'Actualización de software disponible.', from: 'Desarrollo', date: '11/09/2025', body: 'Hay una nueva actualización de software disponible. Descárgala para mejorar tu experiencia.', isSpam: false },
  { id: 15, subject: 'Invitación a evento de networking.', from: 'Organización', date: '10/09/2025', body: 'Te invitamos a nuestro evento de networking para ampliar tu red profesional.', isSpam: false },
  { id: 16, subject: 'Recordatorio: saldo pendiente de pago.', from: 'Cobranzas', date: '09/09/2025', body: 'Tienes un saldo pendiente de pago. Por favor, regulariza tu situación lo antes posible.', isSpam: false },
  { id: 17, subject: 'Bienvenido a la comunidad.', from: 'Equipo de Comunidad', date: '08/09/2025', body: '¡Bienvenido! Ahora eres parte de nuestra comunidad. Explora y participa.', isSpam: false },
  { id: 18, subject: 'Completa tu perfil para más funciones.', from: 'Administración', date: '07/09/2025', body: 'Completa tu perfil para acceder a más funciones y beneficios en la plataforma.', isSpam: false },
  { id: 19, subject: 'Participa en nuestra encuesta anual.', from: 'Investigación', date: '06/09/2025', body: 'Tu opinión es importante. Participa en nuestra encuesta anual y ayúdanos a mejorar.', isSpam: false },
  { id: 20, subject: 'Aviso: mantenimiento el sábado 2-6 AM.', from: 'Infraestructura', date: '05/09/2025', body: 'Habrá mantenimiento programado el sábado de 2 a 6 AM. El servicio podría verse afectado.', isSpam: false },
  { id: 21, subject: 'Nuevo mensaje en tu buzón.', from: 'Sergio Gómez', date: '04/09/2025', body: 'Has recibido un nuevo mensaje en tu buzón. Revisa tu correo para más detalles.', isSpam: false },
  { id: 22, subject: 'Actualización de tu pedido.', from: 'Tienda Online', date: '03/09/2025', body: 'Tu pedido ha sido actualizado. Consulta el estado en tu cuenta.', isSpam: false },
  { id: 23, subject: 'Reunión de seguimiento semanal.', from: 'Coordinación', date: '02/09/2025', body: 'Recuerda la reunión de seguimiento semanal. Agenda y participa.', isSpam: true },
  { id: 24, subject: 'Invitación a grupo de trabajo.', from: 'Marta Ruiz', date: '01/09/2025', body: 'Te invitamos a formar parte de un nuevo grupo de trabajo. Confirma tu asistencia.', isSpam: false },
  { id: 25, subject: 'Confirmación de asistencia evento.', from: 'Eventos', date: '31/08/2025', body: 'Gracias por confirmar tu asistencia al evento. Te esperamos.', isSpam: false },
  { id: 26, subject: 'Password update successful.', from: 'Security', date: '30/08/2025', body: 'Your password has been updated successfully. Keep your account secure.', isSpam: true },
  { id: 27, subject: '新评论在您的帖子。', from: '社交网络', date: '29/08/2025', body: '有人在您的帖子上评论。登录以回复或查看评论。', isSpam: true },
  { id: 28, subject: 'Recordatorio: cita médica mañana.', from: 'Clínica Salud', date: '28/08/2025', body: 'Recuerda tu cita médica programada para mañana. No olvides llevar tu documentación.', isSpam: true },
  { id: 29, subject: 'Your subscription has been renewed.', from: 'Subscriptions', date: '27/08/2025', body: 'Your subscription has been successfully renewed. Enjoy the benefits.', isSpam: true },
  { id: 32, subject: 'Nuevo archivo compartido contigo.', from: 'Carlos Méndez', date: '24/08/2025', body: 'Carlos Méndez ha compartido un archivo contigo. Descárgalo desde tu cuenta.', isSpam: true },
  { id: 35, subject: 'Perfil actualizado.', from: 'Administración', date: '21/08/2025', body: 'Tu perfil ha sido actualizado. Revisa los cambios en tu cuenta.', isSpam: true },
  { id: 36, subject: 'New device access detected.', from: 'Security', date: '20/08/2025', body: 'A new device access has been detected. Please verify your activity.', isSpam: true },
  { id: 38, subject: '技术支持消息。', from: '技术支持', date: '18/08/2025', body: '我们的技术支持团队随时为您提供帮助。', isSpam: true },
  { id: 39, subject: 'Actualización de términos de uso.', from: 'Legal', date: '17/08/2025', body: 'Consulta los nuevos términos de uso que aplican a partir de este mes.', isSpam: false },
  { id: 40, subject: 'Invitación a taller online.', from: 'Talleres', date: '16/08/2025', body: 'Participa en nuestro taller online y mejora tus habilidades profesionales.', isSpam: false },
];
