const WORK_NAME = 'Acme Corp';
const WORK_EMAIL = 'reuniones@acme-corp.com';

export const EMAILS_WORK_LEGIT = [
  { subject: 'Confirmación de reunión', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Sprint Planning". Confirmá aquí: https://calendar.com/confirm?day=1&time=10:00&meeting=Sprint%20Planning', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=1&time=10:00&title=Sprint%20Planning' },
  { subject: 'Reunión de equipo semanal', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Team Sync". Confirmá aquí: https://calendar.com/confirm?day=2&time=11:30&meeting=Team%20Sync', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=2&time=11:30&title=Team%20Sync' },
  { subject: 'Agendado: Revisión de diseño', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "UI Review". Confirmá aquí: https://calendar.com/confirm?day=3&time=15:00&meeting=UI%20Review', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=3&time=15:00&title=UI%20Review' },
  { subject: 'Actualización de proyecto', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Status Update". Confirmá aquí: https://calendar.com/confirm?day=4&time=09:00&meeting=Status%20Update', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=4&time=09:00&title=Status%20Update' },
  { subject: 'Reunión con dirección', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Management Briefing". Confirmá aquí: https://calendar.com/confirm?day=5&time=16:00&meeting=Management%20Briefing', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=5&time=16:00&title=Management%20Briefing' },
  { subject: 'Feedback de sprint anterior', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Retrospectiva". Confirmá aquí: https://calendar.com/confirm?day=6&time=14:00&meeting=Retrospectiva', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=6&time=14:00&title=Retrospectiva' },
  { subject: 'Presentación interna', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Demo Semanal". Confirmá aquí: https://calendar.com/confirm?day=7&time=13:00&meeting=Demo%20Semanal', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=7&time=13:00&title=Demo%20Semanal' },
  { subject: 'Planificación mensual', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Monthly Planning". Confirmá aquí: https://calendar.com/confirm?day=8&time=11:00&meeting=Monthly%20Planning', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=8&time=11:00&title=Monthly%20Planning' },
  { subject: 'Evaluación de desempeño', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Performance Review". Confirmá aquí: https://calendar.com/confirm?day=9&time=10:30&meeting=Performance%20Review', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=9&time=10:30&title=Performance%20Review' },
  { subject: 'Reunión de coordinación', fromName: WORK_NAME, fromEmail: WORK_EMAIL, body: 'Confirmá tu asistencia para "Operaciones Semanales". Confirmá aquí: https://calendar.com/confirm?day=10&time=09:30&meeting=Operaciones%20Semanales', isSpam: false, type: 'work', content: 'apointment', url: 'https://calendar.com/confirm?day=10&time=09:30&title=Operaciones%20Semanales' },
];