// Categorías disponibles (ejemplos): 
// Legit: "work", "friend", "ticket", "finance", "personal", "health", "newsletter", "booking", "admin"
// Spam/Phish: "promo", "scam", "investment", "phishing", "malicious", "social", "fraud"
import { EMAILS_WORK_LEGIT } from './emails_work_legit.js';
import { EMAILS_WORK_SPAM } from './emails_work_spam.js';
import { EMAILS_MEDICAL_LEGIT } from './emails_medical_legit.js';
import { EMAILS_MEDICAL_SPAM } from './emails_medical_spam.js';
import { EMAILS_BESTFRIEND_LEGIT } from './emails_bestfriend_legit.js';
import { EMAILS_BESTFRIEND_SPAM } from './emails_bestfriend_spam.js';

const GIRLFRIEND_NAME = "💚 Cari";
const GIRLFRIEND_EMAIL = "carinacariño@gmail.com";

export const EMAILS = [
  ...EMAILS_WORK_LEGIT,
  ...EMAILS_WORK_SPAM,

  ...EMAILS_MEDICAL_LEGIT,
  ...EMAILS_MEDICAL_SPAM,

  ...EMAILS_BESTFRIEND_LEGIT,
  ...EMAILS_BESTFRIEND_SPAM,

  // { subject: 'Película esta noche?', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Propongo ver esa comedia que te gusta. Palomitas y manta?', isSpam: false, type: 'girlfriend' },
  // { subject: 'Recordatorio médico', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'No te olvides del turno del jueves a las 9:30. Te acompaño si querés.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Gracias por hoy 💛', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'La cena quedó genial. Me encantó cómo cerraste el tema en la reunión.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Plan para mañana', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Si te parece, vamos a caminar al parque y después café. ¿A las 10 te sirve?', isSpam: false, type: 'girlfriend' },
  // { subject: 'Pequeña sorpresa 🎁', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'No te digo nada aún, solo reservá la tarde del sábado.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Necesito tu opinión', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: '¿Cuál te gusta más: la remera azul o la verde? Te mando fotos.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Buena suerte hoy 🍀', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Vas a romperla en la presentación. Estoy segura.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Horario del dentista', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Me cambiaron el turno al miércoles 14:00. Te aviso por si querés venir.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Receta fácil', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Te dejo la receta de la sopa: cebolla, zanahoria, calabaza y un toque de jengibre.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Mensaje rápido', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Llego tarde hoy, guardá algo de la cena porfi.', isSpam: false, type: 'girlfriend' },,
  // { subject: 'Farmacia', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Pasá a buscar paracetamol y vitaminas. Gracias!', isSpam: false, type: 'girlfriend' },
  // // // emails de novia con fotos de gatos
  // { subject: 'Decime si no es tierno', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Subí la foto acá: https://imgur.com/a/1Dfibe1X3rQ', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/01.jpg' },
  // { subject: 'Mirá qué bolita dormida', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Está en la galería: https://flickr.com/photos/cari/2Hfks8Y4t', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/02.jpg' },
  // { subject: 'Este te va a encantar', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Subí la foto aquí: https://drive.google.com/3Jglt9Z5uz594tSk1fEZAHXN2', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/03.jpg' },
  // { subject: 'Amor de gatito', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Mirá esta belleza: https://catpicshare.net/4Khmu0A6va605uTl2gFAAIYO3', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/04.jpg' },
  // { subject: 'Qué cara de inocente 😻', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Te lo mando por acá: https://postimg.cc/5Linv1B7wb7', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/05.jpg' },
  // { subject: 'Desperté con esta vista', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Mirá lo que me encontré: https://ibb.co/6Mopw2C8xc8', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/06.jpg' },
  // { subject: 'No podés creer esto', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Jajaja mirá: https://imgbb.com/7Npqx3D9yd9', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/07.jpg' },
  // { subject: 'Foto del día ✨', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Hoy capturé esta joya: https://drive.google.com/8Oqry4E0ze0', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/08.jpg' },
  // { subject: 'Posando como modelo', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Salió re bien esta: https://unsplash.com/photos/9Prsz5F1af1', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/09.jpg' },
  // { subject: 'Momento de relax', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Qué paz transmite: https://pinterest.com/pin/10Qstu6G2bg', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/10.jpg' },
  // { subject: 'Acá concentrado', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Modo cazador activado: https://imgur.com/a/11Rtuv7H3ch', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/11.jpg' },
  // { subject: 'Siesta profunda', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Mira cómo duerme: https://flickr.com/photos/cari/12Suvw8I4di', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/12.jpg' },
  // { subject: 'Travesura detectada', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Casi me hace reír en zoom: https://postimages.org/13Tvwx9J5ej', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/13.jpg' },
  // { subject: 'Mirada profunda', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Esos ojitos me matan: https://imgbb.com/14Uwxy0K6fk', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/14.jpg' },
  // { subject: 'Rey del sofá', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Se adueñó del sillón: https://catlover.gallery/15Vxyz1L7gl', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/15.jpg' },
  // { subject: 'Jugando con luz', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Le encanta el reflejo: https://drive.google.com/16Wyza2M8hm', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/16.jpg' },
  // { subject: 'Escondite fallido', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Pensó que no lo veía: https://imgur.com/a/17Xzab3N9in', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/17.jpg' },
  // { subject: 'Momento zen', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Meditando felino: https://unsplash.com/photos/18Yabc4O0jo', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/18.jpg' },
  // { subject: 'Explorando rincones', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Siempre curioso: https://flickr.com/photos/cari/19Zbcd5P1kp', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/19.jpg' },
  // { subject: 'Belly rubs time', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Modo pancita arriba: https://postimg.cc/20Acde6Q2lq', isSpam: false, type: 'girlfriend', content: 'picture', url: 'cats/20.jpg' },
  // { subject: 'Recordá llamar a mamá', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Hoy es el cumple de mamá, no te olvides de saludarla.', isSpam: false, type: 'girlfriend' },
  // { subject: 'Buenas noches 😘', fromName: GIRLFRIEND_NAME, fromEmail: GIRLFRIEND_EMAIL, body: 'Que descanses y sueñes lindo.', isSpam: false, type: 'girlfriend' },
  // // // emails de falsa novia (spam)
  // { subject: 'Decime si no es tierno', fromName: GIRLFRIEND_NAME, fromEmail: 'photoalerts@catgallerypics.com', body: 'Subí la foto acá: https://imgur.com/a/1Dfibe1X3rQ', isSpam: true, type: 'promo' },
  // { subject: 'Mirá qué bolita dormida', fromName: GIRLFRIEND_NAME, fromEmail: 'sweetshots@meowdrop.io', body: 'Está en la galería: https://flickr.com/photos/cari/2Hfks8Y4t', isSpam: true, type: 'promo' },
  // { subject: 'Este te va a encantar', fromName: GIRLFRIEND_NAME, fromEmail: 'offers@kittyclub.store', body: 'Subí la foto aquí: https://drive.google.com/3Jglt9Z5uz594tSk1fEZAHXN2', isSpam: true, type: 'promo' },
  // { subject: 'Amor de gatito', fromName: GIRLFRIEND_NAME, fromEmail: 'cuteads@pawmarket.net', body: 'Mirá esta belleza: https://catpicshare.net/4Khmu0A6va605uTl2gFAAIYO3', isSpam: true, type: 'promo' },
  // { subject: 'Qué cara de inocente 😻', fromName: GIRLFRIEND_NAME, fromEmail: 'hotdeals@meowpixx.com', body: 'Te lo mando por acá: https://postimg.cc/5Linv1B7wb7', isSpam: true, type: 'promo' },
  // { subject: 'Desperté con esta vista', fromName: GIRLFRIEND_NAME, fromEmail: 'updates@catgalleryhub.com', body: 'Mirá lo que me encontré: https://ibb.co/6Mopw2C8xc8', isSpam: true, type: 'promo' },
  // { subject: 'No podés creer esto', fromName: GIRLFRIEND_NAME, fromEmail: 'newsletter@purrfectoffers.co', body: 'Jajaja mirá: https://imgbb.com/7Npqx3D9yd9', isSpam: true, type: 'promo' },
  // { subject: 'Foto del día ✨', fromName: GIRLFRIEND_NAME, fromEmail: 'promos@dailycatshots.net', body: 'Hoy capturé esta joya: https://drive.google.com/8Oqry4E0ze0', isSpam: true, type: 'promo' },
  // { subject: 'Posando como modelo', fromName: GIRLFRIEND_NAME, fromEmail: 'marketing@catmoments.shop', body: 'Salió re bien esta: https://unsplash.com/photos/9Prsz5F1af1', isSpam: true, type: 'promo' },
  // { subject: 'Momento de relax', fromName: GIRLFRIEND_NAME, fromEmail: 'offers@meowgallery.org', body: 'Qué paz transmite: https://pinterest.com/pin/10Qstu6G2bg', isSpam: true, type: 'promo' },
  // // emails varios legitimos
  // { subject: 'Pago recibido correctamente 💳', fromName: 'Soporte MercadoPago', fromEmail: 'notificaciones@mercadopago.com', body: 'Tu pago por $12.500 fue procesado con éxito. Gracias por utilizar nuestros servicios.', isSpam: false, type: 'finance' },
  // { subject: 'Tu pedido está en camino 🚚', fromName: 'Tienda Online', fromEmail: 'envios@tiendaonline.com', body: 'Tu pedido #4581 fue despachado. Recibirás una actualización cuando esté por llegar.', isSpam: false, type: 'purchase' },
  // { subject: 'Recordatorio de vencimiento', fromName: 'Telecentro', fromEmail: 'facturacion@telecentro.com.ar', body: 'Tu factura vence en 3 días. Evitá recargos realizando el pago a tiempo.', isSpam: false, type: 'service' },
  // { subject: 'Confirmación de suscripción', fromName: 'Spotify', fromEmail: 'noreply@spotify.com', body: 'Tu suscripción Premium se renovará automáticamente el próximo mes.', isSpam: false, type: 'subscription' },
  // { subject: 'Reunión confirmada', fromName: 'Juan Torres', fromEmail: 'juan.torres@empresa.com', body: 'Listo el encuentro de mañana a las 10hs, nos vemos en la sala de siempre.', isSpam: false, type: 'work' },
  // { subject: 'Invitación al evento anual 🎉', fromName: 'RRHH - Acme Corp', fromEmail: 'eventos@acme.com', body: 'Estás invitado al evento anual de la compañía el viernes a las 19hs.', isSpam: false, type: 'work' },
  // { subject: 'Nuevo mensaje de contacto', fromName: 'Formulario Web', fromEmail: 'info@proaestudiocreativo.com', body: 'Recibimos tu consulta, un asesor te contactará en breve.', isSpam: false, type: 'contact' },
  // { subject: 'Entrada confirmada 🎟️', fromName: 'Eventbrite', fromEmail: 'noreply@eventbrite.com', body: 'Tu entrada para “Noche de Circo” está confirmada. Presentá este correo en la puerta.', isSpam: false, type: 'event' },
  // { subject: 'Tu cuenta fue verificada ✅', fromName: 'Google', fromEmail: 'no-reply@google.com', body: 'Se ha completado el proceso de verificación de tu cuenta.', isSpam: false, type: 'account' },
  // { subject: 'Resumen mensual disponible', fromName: 'Banco Nación', fromEmail: 'notificaciones@bna.com.ar', body: 'Ya podés descargar el resumen de tu cuenta corriente del mes de septiembre.', isSpam: false, type: 'finance' },
  // { subject: '¡Feliz cumpleaños! 🎂', fromName: 'RRHH - Acme Corp', fromEmail: 'rrhh@acme.com', body: 'Todo el equipo te desea un excelente día y un gran año por venir.', isSpam: false, type: 'work' },
  // { subject: 'Actualización del sistema', fromName: 'IT Support', fromEmail: 'soporte@empresa.com', body: 'El sistema estará en mantenimiento el sábado de 22:00 a 02:00.', isSpam: false, type: 'work' },
  // { subject: 'Recordatorio de reunión', fromName: 'Agenda Corporativa', fromEmail: 'notificaciones@calendar.com', body: 'Tenés una reunión programada con el equipo de marketing mañana a las 15:00.', isSpam: false, type: 'work' },
  // { subject: 'Comprobante de envío', fromName: 'Andreani', fromEmail: 'tracking@andreani.com', body: 'Tu paquete ha sido entregado al correo y se encuentra en tránsito.', isSpam: false, type: 'logistics' },
  // { subject: 'Factura disponible', fromName: 'Edesur', fromEmail: 'facturacion@edesur.com.ar', body: 'Tu factura de energía eléctrica ya está disponible para su descarga.', isSpam: false, type: 'service' },
  // { subject: 'Confirmación de reserva', fromName: 'Booking.com', fromEmail: 'reservas@booking.com', body: 'Tu reserva en “Hotel Sol y Mar” está confirmada del 10 al 15 de octubre.', isSpam: false, type: 'travel' },
  // { subject: 'Actualización del pedido', fromName: 'Frávega', fromEmail: 'noreply@fravega.com', body: 'Tu pedido fue despachado y llegará en las próximas 48 horas.', isSpam: false, type: 'purchase' },
  // { subject: 'Nuevo comentario en tu publicación', fromName: 'YouTube', fromEmail: 'noreply@youtube.com', body: 'Alguien comentó en tu último video. Entrá a tu cuenta para verlo.', isSpam: false, type: 'social' },
  // { subject: 'Cita confirmada - Barbería Central', fromName: 'Barbería Central', fromEmail: 'turnos@barberiacentral.com', body: 'Tu cita del viernes a las 17:00 fue confirmada. Te esperamos.', isSpam: false, type: 'personal' },
  // { subject: 'Reinicio de contraseña solicitado', fromName: 'GitHub', fromEmail: 'noreply@github.com', body: 'Alguien solicitó un reinicio de contraseña. Si no fuiste vos, ignorá este mensaje.', isSpam: false, type: 'security' },
  // { subject: 'Entrenamiento reprogramado 🏋️', fromName: 'Club FitZone', fromEmail: 'contacto@fitzone.com', body: 'El entrenamiento del jueves pasa al viernes a las 19hs. Nos vemos en la sala 2.', isSpam: false, type: 'personal' },
  // { subject: 'Asado en lo de Leo 🔥', fromName: 'Leonardo Gómez', fromEmail: 'leo.gomez@gmail.com', body: 'Traé algo para tomar, ya tengo la carne. Arrancamos tipo 20hs.', isSpam: false, type: 'friend' },
  // { subject: 'Cumple de Sofi 🎂', fromName: 'Sofía Torres', fromEmail: 'sofi.torres@hotmail.com', body: 'Este sábado hacemos algo tranqui en casa, venite con quien quieras.', isSpam: false, type: 'friend' },
  // { subject: 'Cambio de horario', fromName: 'Yoga Urbana', fromEmail: 'info@yogaurbana.com', body: 'La clase de Vinyasa se moverá a las 18hs a partir del lunes.', isSpam: false, type: 'personal' },
  // { subject: 'Nos vemos hoy?', fromName: 'Mariana Duarte', fromEmail: 'mariana.duarte@gmail.com', body: 'Te pinta una birra después del laburo?', isSpam: false, type: 'friend' },
  // { subject: 'Confirmación de cita', fromName: 'Peluquería Luz', fromEmail: 'turnos@peluquerialuz.com', body: 'Tu turno del martes a las 17hs está confirmado.', isSpam: false, type: 'service' },
  // { subject: 'Nuevo turno asignado', fromName: 'Gimnasio Vital', fromEmail: 'notificaciones@gimnasiovital.com', body: 'Tu clase de spinning fue agendada para el jueves a las 8hs.', isSpam: false, type: 'personal' },
  // { subject: 'Nos juntamos el finde?', fromName: 'Diego Fernández', fromEmail: 'diego.fernandez@gmail.com', body: 'Hace mil que no nos vemos, armamos algo el sábado?', isSpam: false, type: 'friend' },
  // { subject: 'Entrenamiento cancelado', fromName: 'CrossTeam', fromEmail: 'soporte@crossteam.com', body: 'La clase del miércoles fue cancelada por mantenimiento.', isSpam: false, type: 'personal' },
  // { subject: 'Fiesta sorpresa 🎉', fromName: 'Laura Rivas', fromEmail: 'laura.rivas@outlook.com', body: 'No le digas a nadie, pero el sábado le hacemos sorpresa a Nico.', isSpam: false, type: 'friend' },
  // { subject: 'Reunión con el equipo', fromName: 'Camila Vega', fromEmail: 'camila.vega@gmail.com', body: 'Llevá el informe actualizado, lo repasamos juntos.', isSpam: false, type: 'work' },
  // { subject: 'Cine el jueves?', fromName: 'Pablo Martínez', fromEmail: 'pablo.mtz@outlook.com', body: 'Estrenan la nueva de Dune, vamos?', isSpam: false, type: 'friend' },
  // { subject: 'Taller confirmado', fromName: 'Espacio Creativo Lumen', fromEmail: 'contacto@lumen.com', body: 'Tu inscripción al taller de collage fue confirmada.', isSpam: false, type: 'personal' },
  // { subject: 'Charlamos después?', fromName: 'Florencia Navarro', fromEmail: 'flor.navarro@gmail.com', body: 'Te llamo cuando salgo del trabajo así coordinamos.', isSpam: false, type: 'friend' },
  // { subject: 'Recordatorio de sesión', fromName: 'Entrenador Personal Martín', fromEmail: 'martin.fitcoach@gmail.com', body: 'Nos vemos mañana a las 9hs en el parque.', isSpam: false, type: 'personal' },
  // { subject: 'Café pendiente ☕', fromName: 'Lucía Méndez', fromEmail: 'lucia.mendez@outlook.com', body: 'Te debo ese café, estás libre el martes?', isSpam: false, type: 'friend' },
  // { subject: 'Ensayo confirmado 🎭', fromName: 'Grupo Teatral Andamio', fromEmail: 'info@andamio.com', body: 'El ensayo será este viernes a las 19hs en el espacio principal.', isSpam: false, type: 'personal' },
  // { subject: 'Confirmación de pedido', fromName: 'Librería Central', fromEmail: 'ventas@libreriacentral.com', body: 'Tu pedido de libros fue preparado y estará listo para retirar mañana.', isSpam: false, type: 'purchase' },
  // { subject: 'Partido este domingo ⚽', fromName: 'Juan Cruz', fromEmail: 'juan.cruz@gmail.com', body: 'Jugamos a las 17hs en el parque, llevá camiseta roja.', isSpam: false, type: 'friend' },
  // { subject: 'Turno de masaje confirmado 💆', fromName: 'Spa Natural', fromEmail: 'reservas@spanatural.com', body: 'Tu turno para el viernes a las 18hs fue confirmado. Te esperamos.', isSpam: false, type: 'service' },
  // { subject: 'Nuevo ciclo de fotografía 📷', fromName: 'Escuela ArteVisual', fromEmail: 'info@artevisual.com', body: 'Ya podés inscribirte al curso de fotografía digital que arranca en noviembre.', isSpam: false, type: 'education' },
  // { subject: 'Concierto gratuito 🎶', fromName: 'Centro Cultural San Martín', fromEmail: 'eventos@ccsm.com', body: 'El viernes se presenta la Orquesta Joven, entrada libre hasta agotar cupos.', isSpam: false, type: 'event' },
  // { subject: 'Revisión del auto 🚗', fromName: 'Taller El Pistón', fromEmail: 'servicios@elpiston.com', body: 'Recordá tu turno para el cambio de aceite el jueves a las 10hs.', isSpam: false, type: 'service' },
  // { subject: 'Reunión de consorcio', fromName: 'Administración Mitre 2250', fromEmail: 'admin@mitre2250.com', body: 'El encuentro mensual será el martes a las 19hs en planta baja.', isSpam: false, type: 'community' },
  // { subject: 'Clases de cocina 🧑‍🍳', fromName: 'Escuela Gourmet', fromEmail: 'cursos@escuelagourmet.com', body: 'Abrimos inscripción para el taller de pastas caseras. Cupos limitados.', isSpam: false, type: 'education' },
  // { subject: 'Reunión familiar ❤️', fromName: 'Tía Norma', fromEmail: 'norma.rios@gmail.com', body: 'Este domingo hacemos almuerzo en casa, traé postre.', isSpam: false, type: 'family' },
  // { subject: 'Limpieza programada', fromName: 'Edificio Rivadavia 880', fromEmail: 'notificaciones@rivadavia880.com', body: 'El servicio de limpieza profunda será el sábado por la mañana.', isSpam: false, type: 'community' },
  // { subject: 'Invitación a voluntariado 🌱', fromName: 'Fundación Verde', fromEmail: 'voluntariado@fundacionverde.org', body: 'Nos reunimos el domingo a las 9hs en el parque para plantar árboles.', isSpam: false, type: 'social' },
  // { subject: 'Entrega de certificado', fromName: 'Cursos Online EduPro', fromEmail: 'noreply@edupro.com', body: 'Tu certificado del curso de diseño UX ya está disponible para descarga.', isSpam: false, type: 'education' },
  // { subject: 'Aviso de mantenimiento', fromName: 'Aysa', fromEmail: 'comunicaciones@aysa.com.ar', body: 'El suministro de agua se interrumpirá mañana de 8 a 12hs por obras.', isSpam: false, type: 'service' },
  // { subject: 'Clase de prueba gratuita 🎨', fromName: 'Estudio Arte Libre', fromEmail: 'contacto@artelibre.com', body: 'Te esperamos el martes a las 18hs para la clase abierta de pintura.', isSpam: false, type: 'education' },
  // { subject: 'Fiesta de disfraces 🎭', fromName: 'Clara Benítez', fromEmail: 'clara.benitez@outlook.com', body: 'Traé disfraz y buena onda, el sábado a las 21hs en casa.', isSpam: false, type: 'friend' },
  // { subject: 'Actualización del contrato', fromName: 'Inmobiliaria Plaza', fromEmail: 'info@inmobiliariaplaza.com', body: 'Adjuntamos nueva versión del contrato para su revisión y firma.', isSpam: false, type: 'work' },
  // { subject: 'Nuevo horario de clases', fromName: 'Instituto de Idiomas Babel', fromEmail: 'idiomas@babel.com', body: 'A partir de noviembre, la clase de inglés avanzado será los miércoles 19hs.', isSpam: false, type: 'education' },
  // { subject: 'Nuevas actividades en el club 🏊', fromName: 'Club Social Belgrano', fromEmail: 'noticias@clubbelgrano.com', body: 'Se suma natación para adultos y yoga al aire libre. Consultá en recepción.', isSpam: false, type: 'community' },
  // { subject: 'Tu turno con el contador', fromName: 'Estudio Contable Ferraro', fromEmail: 'contacto@ferraro.com', body: 'Te esperamos el jueves a las 15hs para revisar las declaraciones.', isSpam: false, type: 'work' },
  // { subject: 'Invitación al webinar 💻', fromName: 'TechLatam', fromEmail: 'eventos@techlatam.com', body: 'Únete al webinar “Tendencias de IA 2025” el miércoles 10hs.', isSpam: false, type: 'education' },
  // { subject: 'Nueva receta semanal 🍝', fromName: 'Revista Buen Comer', fromEmail: 'news@buencomer.com', body: 'Probá esta lasaña de berenjenas increíble. Enviamos la lista de ingredientes.', isSpam: false, type: 'lifestyle' },
  // { subject: 'Turno veterinario confirmado 🐾', fromName: 'Clínica Animalia', fromEmail: 'turnos@animalia.com', body: 'Tu consulta con Dr. Romero fue confirmada para el viernes a las 17hs.', isSpam: false, type: 'service' },
  // { subject: 'Encuentro de lectura 📚', fromName: 'Biblioteca Popular Alberdi', fromEmail: 'contacto@bibalberdi.org', body: 'El club de lectura se reúne este sábado a las 18hs para charlar sobre Cortázar.', isSpam: false, type: 'community' },
  // // mails varios spam
  // { subject: 'Tu cuenta será suspendida ⚠️', fromName: 'Atención al Cliente', fromEmail: 'security@paycenter-alerts.biz', body: 'Verificá tu identidad antes de que se bloquee tu cuenta: https://paycenter-secure.net/login', isSpam: true, type: 'security' },
  // { subject: 'Oferta exclusiva 🔥', fromName: 'ShopNow Deals', fromEmail: 'promo@shopnow-limited.co', body: 'Get 90% OFF today only! Confirm here: https://shopnow-sale.com/claim', isSpam: true, type: 'promo' },
  // { subject: 'Ganaste un sorteo 🎁', fromName: 'Sorteos Express', fromEmail: 'rewards@premios-fast.info', body: 'Reclamá tu premio ahora: https://premios-fast.info/confirm?code=WIN2025', isSpam: true, type: 'promo' },
  // { subject: 'Factura pendiente de pago', fromName: 'Telecom Servicios', fromEmail: 'facturacion@telecom-alertas.co', body: 'Regularizá tu factura vencida acá: https://telecom-payments.co/factura', isSpam: true, type: 'service' },
  // { subject: 'Premium access unlocked 🎬', fromName: 'StreamFlix', fromEmail: 'noreply@streamflix-premium.fun', body: 'Confirm your free month of Premium here: https://streamflix-premium.fun/login', isSpam: true, type: 'entertainment' },
  // { subject: '送货问题通知', fromName: '中国邮政', fromEmail: 'delivery@china-post.cn.com', body: '请在24小时内确认您的订单信息: https://china-post.cn.com/verify', isSpam: true, type: 'logistics' },
  // { subject: 'Reembolso disponible 💰', fromName: 'Banco Federal', fromEmail: 'refunds@bancofederal-support.org', body: 'Podés reclamar tu reembolso desde: https://bancofederal-support.org/refund', isSpam: true, type: 'finance' },
  // { subject: 'Suspicious login detected', fromName: 'Google Security', fromEmail: 'alert@google-verif.net', body: 'We noticed a new login attempt. Verify now: https://google-verif.net/check', isSpam: true, type: 'security' },
  // { subject: '新品发布会邀请函', fromName: '华为技术有限公司', fromEmail: 'events@huawei-promo.cn', body: '点击这里获取邀请函: https://huawei-promo.cn/event', isSpam: true, type: 'promo' },
  // { subject: 'Crypto Investment Alert 🚀', fromName: 'CoinBoost', fromEmail: 'alerts@coinboost-invest.io', body: 'Join our new high-yield plan now: https://coinboost-invest.io/start', isSpam: true, type: 'finance' },
  // { subject: 'Envio retenido en aduana 📦', fromName: 'Correo Argentino', fromEmail: 'support@correo-argentina.co', body: 'Pagá la tasa de liberación para recibir tu paquete: https://correo-argentina.co/pago', isSpam: true, type: 'logistics' },
  // { subject: 'Get your NFT reward 🎨', fromName: 'MetaArts', fromEmail: 'support@metaarts-nft.biz', body: 'Claim your free NFT drop: https://metaarts-nft.biz/claim', isSpam: true, type: 'promo' },
  // { subject: 'Aprobación de crédito rápida', fromName: 'Créditos Ya!', fromEmail: 'offers@creditoya-finance.org', body: 'Obtené tu préstamo en minutos: https://creditoya-finance.org/apply', isSpam: true, type: 'finance' },
  // { subject: '免费获取会员', fromName: '优酷视频', fromEmail: 'vip@youku-cn.vip', body: '点击此处立即激活: https://youku-cn.vip/active', isSpam: true, type: 'entertainment' },
  // { subject: 'Tu paquete no pudo ser entregado', fromName: 'DHL Express', fromEmail: 'notify@dhl-trackers.pro', body: 'Reprogramá la entrega acá: https://dhl-trackers.pro/reenvio', isSpam: true, type: 'logistics' },
  // { subject: 'Your Apple ID has been locked 🍎', fromName: 'Apple Support', fromEmail: 'security@apple-verify.co', body: 'To unlock your account, click here: https://apple-verify.co/unlock', isSpam: true, type: 'security' },
  // { subject: 'Actualización de seguridad pendiente', fromName: 'Microsoft Update', fromEmail: 'notices@ms-securepatch.net', body: 'Descargá la actualización crítica: https://ms-securepatch.net/update', isSpam: true, type: 'security' },
  // { subject: '中奖通知 🎉', fromName: '支付宝官方', fromEmail: 'service@alipay-cn.com', body: '您获得了现金奖励，请点击确认: https://alipay-cn.com/prize', isSpam: true, type: 'promo' },
  // { subject: 'Verificación urgente requerida', fromName: 'AFIP Argentina', fromEmail: 'alertas@afip-control.ar.net', body: 'Ingresá tus datos para evitar sanciones: https://afip-control.ar.net/verificar', isSpam: true, type: 'finance' },
  // { subject: 'Entrega fallida - UPS', fromName: 'UPS Delivery', fromEmail: 'status@ups-delivery.me', body: 'Tu paquete fue devuelto. Confirmá los datos de envío: https://ups-delivery.me/retry', isSpam: true, type: 'logistics' },
  // { subject: 'Activa tu premio ahora 🎁', fromName: 'PromoClub', fromEmail: 'promo@claim-now.xyz', body: 'Has sido seleccionado. Reclama aquí: https://claim-now.xyz/redeem', isSpam: true, type: 'promo' },
  // { subject: 'Cuenta en riesgo — Acción requerida', fromName: 'Soporte', fromEmail: 'security@account-check.info', body: 'Hemos detectado actividad inusual. Verificá tu cuenta: https://account-check.info/verify', isSpam: true, type: 'security' },
  // { subject: 'Última oferta — 95% OFF', fromName: 'MegaShop', fromEmail: 'offers@megashop-deals.co', body: 'Solo por hoy: accedé y ahorrá: https://megashop-deals.co/sale', isSpam: true, type: 'promo' },
  // { subject: 'Reembolso pendiente', fromName: 'Banco Express', fromEmail: 'payments@banco-express.club', body: 'Hay un reembolso a tu nombre, ingresá tus datos: https://banco-express.club/refund', isSpam: true, type: 'finance' },
  // { subject: 'Verifica tu entrega', fromName: 'Paquetería', fromEmail: 'notify@fast-delivery-info.net', body: 'Tu envío está retenido. Reprogramá la entrega: https://fast-delivery-info.net/track', isSpam: true, type: 'logistics' },
  // { subject: 'Free trial activated', fromName: 'ProTool', fromEmail: 'trial@protool-free.fun', body: 'Start your 30-day trial now: https://protool-free.fun/start', isSpam: true, type: 'promo' },
  // { subject: '您有一笔未领取的款项', fromName: '中国支付', fromEmail: 'service@cn-payments.cn', body: '请提交信息领取: https://cn-payments.cn/claim', isSpam: true, type: 'finance' },
  // { subject: 'Confirma tu compra', fromName: 'TiendaX', fromEmail: 'orders@tiendax-online.biz', body: 'Se registró una compra, confirmá aquí: https://tiendax-online.biz/confirm', isSpam: true, type: 'purchase' },
  // { subject: 'Secure your account now', fromName: 'Account Team', fromEmail: 'security@protect-account.co', body: 'Reset your password immediately: https://protect-account.co/reset', isSpam: true, type: 'security' },
  // { subject: 'Gana criptomonedas hoy 🚀', fromName: 'CryptoWin', fromEmail: 'join@cryptowin-earn.io', body: 'Invierte $50 y multiplica: https://cryptowin-earn.io/join', isSpam: true, type: 'finance' },
  // { subject: 'Nuevo mensaje importante', fromName: 'Notificaciones', fromEmail: 'alerts@message-center.pro', body: 'Tenés un mensaje pendiente, leelo aquí: https://message-center.pro/view', isSpam: true, type: 'social' },
  // { subject: 'Oferta VIP limitada', fromName: 'ClubVIP', fromEmail: 'vip@exclusive-deals.us', body: 'Acceso anticipado para socios: https://exclusive-deals.us/vip', isSpam: true, type: 'promo' },
  // { subject: '确认您的订单', fromName: '速购', fromEmail: 'order@fastbuy-cn.com', body: '请确认您的订单信息: https://fastbuy-cn.com/confirm', isSpam: true, type: 'purchase' },
  // { subject: 'You won a gift card!', fromName: 'GiftCard Team', fromEmail: 'winner@giftcard-claim.org', body: 'Claim your $100 gift card: https://giftcard-claim.org/claim', isSpam: true, type: 'promo' },
  // { subject: 'Problema con tu factura', fromName: 'Servicios', fromEmail: 'billing@service-payments.co', body: 'Evita cortes, actualizá tu pago aquí: https://service-payments.co/pay', isSpam: true, type: 'service' },
  // { subject: 'Reclama tu cupón ahora', fromName: 'CupónExpress', fromEmail: 'cupon@couponexpress.store', body: 'Solo 100 cupones disponibles: https://couponexpress.store/redeem', isSpam: true, type: 'promo' },
  // { subject: 'Alert: suspicious activity', fromName: 'Security Team', fromEmail: 'alert@secure-checks.net', body: 'Confirm the recent activity: https://secure-checks.net/confirm', isSpam: true, type: 'security' },
  // { subject: '免费会员领取', fromName: '视频平台', fromEmail: 'vip@vip-activate.cn', body: '点击激活您的免费会员: https://vip-activate.cn/activate', isSpam: true, type: 'entertainment' },
  // { subject: 'Activa tu método de pago', fromName: 'Sistema de Pagos', fromEmail: 'payments@verify-payments.io', body: 'Actualizá tu medio de pago para evitar interrupciones: https://verify-payments.io/update', isSpam: true, type: 'finance' },
  // { subject: 'Limited time: access premium', fromName: 'StreamNow', fromEmail: 'access@streamnow-premium.me', body: 'Unlock premium features now: https://streamnow-premium.me/unlock', isSpam: true, type: 'entertainment' },
  // { subject: 'Ganaste un auto 🚗', fromName: 'Sorteos Online', fromEmail: 'premios@winbig-prize.co', body: 'Fuiste elegido al azar. Reclamá tu vehículo hoy mismo: https://winbig-prize.co/claim', isSpam: true, type: 'promo' },
  // { subject: 'Cuenta bloqueada temporalmente ⚠️', fromName: 'Soporte Técnico', fromEmail: 'support@secure-access.info', body: 'Necesitamos verificar tu cuenta antes de 24hs: https://secure-access.info/verify', isSpam: true, type: 'security' },
  // { subject: 'Oferta solo por hoy 💥', fromName: 'MegaDescuentos', fromEmail: 'promo@ofertas-limitadas.biz', body: 'Todo al 95% de descuento, entrá antes de que termine: https://ofertas-limitadas.biz/sale', isSpam: true, type: 'promo' },
  // { subject: 'Alerta: pago no procesado', fromName: 'Finanzas Express', fromEmail: 'alerts@paycenter-update.net', body: 'Tu último pago fue rechazado, ingresá nuevamente tus datos: https://paycenter-update.net/retry', isSpam: true, type: 'finance' },
  // { subject: 'Get free followers 💫', fromName: 'SocialBoost', fromEmail: 'growth@socialboost.io', body: 'Increase your followers instantly with this special promo: https://socialboost.io/gain', isSpam: true, type: 'promo' },
  // { subject: '¡Sos el cliente número 1000!', fromName: 'Tienda Éxito', fromEmail: 'rewards@tienda-exito.pro', body: 'Ganaste un cupón de $5000, reclamalo antes de medianoche: https://tienda-exito.pro/winner', isSpam: true, type: 'promo' },
  // { subject: 'Confirmación de pago pendiente', fromName: 'Banco Privado', fromEmail: 'billing@bancoprivado-pay.co', body: 'Debés validar tu transferencia para evitar suspensión: https://bancoprivado-pay.co/validar', isSpam: true, type: 'finance' },
  // { subject: 'Lucky day bonus 🎰', fromName: 'Casino Royale', fromEmail: 'bonus@casinoroyale-play.net', body: 'Get 200 free spins just for logging in today: https://casinoroyale-play.net/free', isSpam: true, type: 'entertainment' },
  // { subject: 'Tu envío está retenido', fromName: 'Correo Internacional', fromEmail: 'service@parcel-holdings.org', body: 'Pagá la tasa de liberación y recibe tu paquete sin demora: https://parcel-holdings.org/pago', isSpam: true, type: 'logistics' },
  // { subject: '工作机会邀请函', fromName: '招聘部', fromEmail: 'job@cn-career.cn', body: '我们提供高薪远程工作，立即申请: https://cn-career.cn/apply', isSpam: true, type: 'promo' },
  // { subject: 'Verificación de identidad requerida', fromName: 'AFIP', fromEmail: 'alertas@afip-arg.com', body: 'Ingresá tu número de CUIT para confirmar tu identidad: https://afip-arg.com/verify', isSpam: true, type: 'security' },
  // { subject: 'Your Amazon package is delayed 📦', fromName: 'Amazon Shipping', fromEmail: 'notify@amazon-ships.co', body: 'Click here to reschedule your delivery: https://amazon-ships.co/update', isSpam: true, type: 'logistics' },
  // { subject: 'Crédito preaprobado 💸', fromName: 'Préstamos Ya', fromEmail: 'ofertas@prestamos-ya.pro', body: 'Obtené hasta $300.000 sin requisitos, ingresá ahora: https://prestamos-ya.pro/aplica', isSpam: true, type: 'finance' },
  // { subject: '新品上架优惠', fromName: '天猫商城', fromEmail: 'sales@tmall-cn.com', body: '本周新品享受五折优惠，限时抢购: https://tmall-cn.com/deals', isSpam: true, type: 'promo' },
  // { subject: 'Nueva herramienta de trading 💹', fromName: 'CryptoTradePro', fromEmail: 'support@cryptotradepro.info', body: 'Ganá más con nuestro bot automatizado: https://cryptotradepro.info/join', isSpam: true, type: 'finance' },
  // { subject: 'Problema con tu cuenta PayPal', fromName: 'PayPal Team', fromEmail: 'security@paypal-update.biz', body: 'Verificá tu identidad para evitar bloqueo: https://paypal-update.biz/login', isSpam: true, type: 'security' },
  // { subject: 'Reembolso disponible 💰', fromName: 'Banco Federal', fromEmail: 'refunds@bancofederal-support.org', body: 'Reclamá tu reembolso ingresando a: https://bancofederal-support.org/refund', isSpam: true, type: 'finance' },
  // { subject: 'Confirmación de suscripción', fromName: 'MusicWorld', fromEmail: 'offers@musicworld-premium.me', body: 'Activa tu plan Premium con 70% OFF: https://musicworld-premium.me/offer', isSpam: true, type: 'entertainment' },
  // { subject: '中奖通知 🎉', fromName: '支付宝官方', fromEmail: 'service@alipay-cn.com', body: '您获得了现金奖励，请点击确认: https://alipay-cn.com/prize', isSpam: true, type: 'promo' },
  // { subject: 'Entrega fallida - UPS', fromName: 'UPS Delivery', fromEmail: 'status@ups-delivery.me', body: 'Tu paquete fue devuelto. Confirmá los datos de envío: https://ups-delivery.me/retry', isSpam: true, type: 'logistics' }
];
